### ISSUE TITLE
Possibility to change sound.wav

### ISSUE THREAD

**Issue by Zeleron** [Ivaylo-Lafchiev/tarkov-kill-detector#1]
With no knowledge of running python on windows it would be nice if we can change the sound. The script works perfectly, but i would like to change the sound though :)

**Comment by Ivaylo-Lafchiev** [comment]
Check the latest tag, let me know if that solves the problem for you.
https://github.com/Ivaylo-Lafchiev/tarkov-kill-detector/releases/tag/0.0.3

**Comment by Zeleron** [comment]
i tried changing the sound.wav file in the directory but it doesnt play. I get the windows error notification sound instead. Does the file need a certain permission? im not able to move the sound after i copy it in.

**Comment by Zeleron** [comment]
im testing one thing. I might have put the file the wrong place ...

**Comment by Zeleron** [comment]
its using the file from the temp. C:\Users\denni\AppData\Local\Temp\_MEI12362\sound.wav - Could you make so that it uses a sound file from C:\Users\denni\AppData\Local\Temp\Highlights\Escape From Tarkov instead. That way you can put the sound file in a place it doesnt get deleted from ?

**Comment by Ivaylo-Lafchiev** [comment]
Did you try putting the sound file in the same directory as the executable? That's where it looks for the file.

**Comment by Zeleron** [comment]
ill try just one sec

**Comment by Zeleron** [comment]
You are an absolute rockstar.. Works perfect now ;)

**Comment by Zeleron** [comment]
Just make sure to write where to put the sound file.... Now its time to playaround with voice commands for kills :P
